# Generated by Django 4.2.20 on 2026-03-19 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='trans_desc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
