# Generated by Django 4.2.20 on 2026-03-19 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction1', '0002_transaction_trans_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='account_no',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
