# Generated by Django 4.2.20 on 2026-03-19 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank1', '0002_customuser_delete_userdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='account_no',
            field=models.CharField(blank=True, max_length=4, null=True, unique=True),
        ),
    ]
