# Generated by Django 4.2.20 on 2026-03-24 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chat1', '0002_user_friends'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
